export const lightTheme = {
    '--primary-color': '#1890ff',
    '--background-color': '#ffffff',
    '--text-color': 'rgba(0, 0, 0, 0.85)',
    '--secondary-color': '#52c41a',
    '--header-text-color': '#ffffff',
    '--border-color': '#d9d9d9',
    '--focus-color': '#1890ff',
    '--scrollbar-track-color': '#f1f1f1',
    '--scrollbar-thumb-color': '#888',
    '--scrollbar-thumb-hover-color': '#555',
    '--layout-background-color': '#ffffff',
    '--header-background-color': '#1890ff',
    '--link-color': '#1890ff',
    '--background-gradient-start': '#ffffff',
    '--background-gradient-end': '#e0e0e0',
    '--cube-border-color': '#1890ff',
    '--cube-border-alt-color': '#52c41a',
    '--button-background-color': '#ffffff',
    '--button-border-color': '#d9d9d9',
    '--button-hover-background-color': '#f0f0f0',
    '--button-hover-border-color': '#1890ff',
    '--heading-text-color': '#000000', /* New addition for headings */
};

export const darkTheme = {
    '--primary-color': '#1890ff',
    '--background-color': '#1e1e1e',
    '--text-color': '#ffffff',
    '--secondary-color': '#52c41a',
    '--header-text-color': '#ffffff',
    '--border-color': '#444444',
    '--focus-color': '#1890ff',
    '--scrollbar-track-color': '#333333',
    '--scrollbar-thumb-color': '#555555',
    '--scrollbar-thumb-hover-color': '#777777',
    '--layout-background-color': '#2b2b2b',
    '--header-background-color': '#333333',
    '--link-color': '#1890ff',
    '--background-gradient-start': '#2b2b2b',
    '--background-gradient-end': '#1e1e1e',
    '--cube-border-color': '#1d1d1d',
    '--cube-border-alt-color': '#52c41a',
    '--button-background-color': '#333333',
    '--button-border-color': '#555555',
    '--button-hover-background-color': '#444444',
    '--button-hover-border-color': '#1890ff',
    '--heading-text-color': '#ffffff', /* New addition for headings */
};
